steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/onegraph-prod/onegraph-changelog-staging', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/onegraph-prod/onegraph-changelog-staging']

images: ['gcr.io/onegraph-prod/onegraph-changelog-staging']
